# Generated by Django 3.1.5 on 2021-01-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
